class Array {
    public static void main(String[] args){
        int[] score = new int [3];
        score[0] = 100;
        score[2] = 60;

        String[] name = {"湯浅","長島"};

        System.out.println(name[0] + "は" + score[0] + "点です");
        system.out.println(name[1] + "は" + score[1] + "点です");
        System.out.println(name[2] + "は" + score[2] + "点です");
        System.out.println("受験者数は" + score.length + "人です")
    }
}
